---
- hosts: localhost

  tasks:
    - name: Dieser Task w√ºrde normalerweise fehlschlagen...
      command: /bin/false
      changed_when: false
      ignore_errors: true    # ...deswegen aber nicht!
